pluginManagement {
    repositories {
        gradlePluginPortal()
        maven { url = 'https://maven.neoforged.net/releases/' }
        mavenCentral()
    }
}

dependencyResolutionManagement {
    repositories {
        mavenCentral()
        maven { url = 'https://maven.neoforged.net/releases/' }
    }
}

rootProject.name = 'zenith'
