modLoader="javafml"
loaderVersion="${neoforge_loader_version_range}"
license="MIT"
issueTrackerURL="https://github.com/atomos/zenith/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
description="${mod_description}"
authors="${mod_authors}"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="${neoforge_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"
